#!/usr/bin/env bash

# Install and configure Nginx on web servers to add custom header to HTTP response
# Custom header name is X-Served-By, with value set to the hostname of the server Nginx is running on

# Install Nginx web server and update firewall settings to allow requests through port 80
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Create necessary directories and files for Nginx
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx to redirect a single page and add custom header with hostname
server_block="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sudo sed -i "s/server_name _;/$server_block/" /etc/nginx/sites-enabled/default

# Configure Nginx to redirect 404 errors to a custom error page
error_block="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$error_block/" /etc/nginx/sites-enabled/default

# Restart Nginx web server to apply configuration changes
sudo service nginx restart