#!/usr/bin/env bash
# This script replaces the default Nginx configuration file with a copy of another file, using a symbolic link.
# The -f flag is used to force the replacement of the existing file, if it exists.
NGINX_CONF_DIR="/etc/nginx"
sudo ln -sf "${NGINX_CONF_DIR}/sites-available/default" "${NGINX_CONF_DIR}/sites-enabled/default"
sudo service nginx restart
